server:
  port: 9191

spring:
  application:
    name: jgt-ms-gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: jgt-ms-pago
          uri: lb://jgt-ms-pago
          predicates:
            - Path=/pago/**
          filters:
            - name: AuthFilter
        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**
          filters: []



eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8181/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}